import Head from 'next/head'
import { useEffect, useState } from "react";
import Left from '../component/weather/left'


export default function Home() {
  const [weather, setWeather] = useState();
  const [city, setCity] = useState("London");
  const handleClick=(city)=>{
setCity(city)
  }

  useEffect(() => {
    fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=0c3c4c7ca3b7f1f6cbca381461204e9e`
    )
      .then((res) => res.json())
      .then((res) => {
        setWeather(res);
      })
      .catch((err) => console.error(err));
    console.log(weather);
  }, [city]);
  if (!weather) {
    return <div>Loading...</div>;
  }
  return (
    <div className='whole'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Left weather={weather} handleClick={handleClick} />
     
    </div>
  )
}